"""
script_io.py — Export the GUI configuration as a standalone Python script that
calls saira() directly, and load such a script (or a hand-written one) back
into the GUI.

Loading does not parse the script's text: it runs the script with stand-ins for
saira() and read_idx_defs() that only record their arguments, so any variables
or expressions in the script are resolved by Python itself. Since this executes
the script's own code, only load scripts you trust — the same trust level as
running `python your_script.py` yourself.
"""

import contextlib
import importlib
import inspect
import io
import os
from datetime import datetime

import numpy as np
import pandas as pd

# Order in which the saira() arguments are written in exported scripts
_ARG_ORDER = (
    "filename", "path_to_files", "file_extension", "IndexDefs", "output_file",
    "do_redshift", "z",
    "do_resolution", "sigma_ini", "FWHM_ini", "R_ini", "sigma_fin", "FWHM_fin", "R_fin",
    "simulate", "error", "error_method", "use_flags", "mask_regions", "bpr_thres",
    "negative_Ew_to_zero", "A_to_mag", "compute_idx",
    "path_singleind_plots", "AllIndicesPlot", "allindices_plot_path", "print_log",
)


class ScriptImportError(Exception):
    """Raised when a script can't be run, or never calls saira()."""


def generate_script(kwargs: dict, selected_indices=None) -> str:
    """
    Render the saira() call described by kwargs as standalone Python source.
    kwargs["IndexDefs"] must be the path of the index definitions file; if
    selected_indices is given, only those indices are measured.
    """
    index_defs = kwargs["IndexDefs"]
    lines = [
        '"""',
        f"Auto-generated by the SAIRA GUI on {datetime.now():%Y-%m-%d %H:%M}.",
        "",
        "Standalone script: reproduces, outside the GUI, exactly the run that was",
        "configured in it. Safe to edit by hand and re-run (e.g. on a cluster), and",
        "it can be loaded back into the GUI with 'Load Script (.py)'.",
        '"""',
        "",
    ]
    if selected_indices is not None:
        lines += ["import numpy as np", "", "from saira import saira",
                  "from saira.SairaFunctions import read_idx_defs", ""]
    else:
        lines += ["from saira import saira", ""]

    lines += [f"INDEX_DEFS = {index_defs!r}"]
    if selected_indices is not None:
        lines += ["", "# Indices chosen with 'Select Indices…'",
                  f"SELECTED_INDICES = {[str(n) for n in selected_indices]!r}"]
    lines += ["", "", "def run():"]
    if selected_indices is not None:
        lines += ["    index_defs = read_idx_defs(INDEX_DEFS)",
                  "    index_defs = index_defs[np.isin(index_defs['name'], SELECTED_INDICES)]"]
        index_arg = "index_defs"
    else:
        index_arg = "INDEX_DEFS"

    lines.append("    result = saira(")
    for key in _ARG_ORDER + tuple(k for k in kwargs if k not in _ARG_ORDER):
        if key not in kwargs or kwargs[key] is None:
            continue
        value = index_arg if key == "IndexDefs" else repr(kwargs[key])
        lines.append(f"        {key}={value},")
    lines += [
        "    )",
        "    return result",
        "",
        "",
        'if __name__ == "__main__":',
        "    print(run())",
        "",
    ]
    return "\n".join(lines)


def import_script(path: str) -> tuple:
    """
    Run the script at `path` with a recording saira() and return
    (kwargs, index_defs_path, selected_indices, warnings), where kwargs are the
    arguments of the last saira() call, index_defs_path the index definitions
    file and selected_indices the names of the measured indices when the script
    passes a filtered set of definitions (None otherwise).
    Raises ScriptImportError if the script can't be run or never calls saira().
    """
    saira_pkg = importlib.import_module("saira")
    wrapper_mod = importlib.import_module("saira.saira_wapper")
    functions_mod = importlib.import_module("saira.SairaFunctions")

    real_saira = wrapper_mod.saira
    real_read_idx_defs = functions_mod.read_idx_defs
    signature = inspect.signature(real_saira)
    calls, read_paths = [], []

    def recording_saira(*args, **kw):
        bound = signature.bind(*args, **kw)
        calls.append(dict(bound.arguments))
        return pd.DataFrame()

    def recording_read_idx_defs(ref_table):
        read_paths.append(ref_table)
        return real_read_idx_defs(ref_table)

    patched = [(saira_pkg, "saira", recording_saira), (wrapper_mod, "saira", recording_saira),
               (functions_mod, "read_idx_defs", recording_read_idx_defs),
               (wrapper_mod, "read_idx_defs", recording_read_idx_defs)]
    originals = [(mod, name, getattr(mod, name)) for mod, name, _ in patched]
    for mod, name, stand_in in patched:
        setattr(mod, name, stand_in)
    try:
        with open(path, "r", encoding="utf-8") as f:
            source = f.read()
        namespace = {"__name__": "__main__", "__file__": path}
        try:
            with contextlib.redirect_stdout(io.StringIO()):   # the script's own prints
                exec(compile(source, path, "exec"), namespace)
        except Exception as e:
            raise ScriptImportError(f"Error while running '{os.path.basename(path)}': {e}") from e
    finally:
        for mod, name, original in originals:
            setattr(mod, name, original)

    if not calls:
        raise ScriptImportError("The script ran but never called saira() — nothing to import.")

    warnings = []
    if len(calls) > 1:
        warnings.append(f"The script calls saira() {len(calls)} times; only the last call was imported.")
    kwargs = calls[-1]

    index_defs = kwargs.get("IndexDefs")
    selected = None
    if isinstance(index_defs, str):
        index_defs_path = index_defs
    elif isinstance(index_defs, np.ndarray) and index_defs.dtype.names and "name" in index_defs.dtype.names:
        selected = [str(n) for n in index_defs["name"]]
        index_defs_path = read_paths[-1] if read_paths else None
        if index_defs_path is None:
            warnings.append("The index definitions were built in the script without read_idx_defs(); "
                            "choose the .ind file by hand.")
    else:
        index_defs_path = None
        warnings.append("The script does not give IndexDefs; choose the index definitions by hand.")

    return kwargs, index_defs_path, selected, warnings
